#!/bin/sh

# /usr/bin/xinput set-prop 11 277 -111 -111
# /usr/bin/xkbcomp /home/lbakken/.xkb :0

logdir=/home/lbakken/log
logfile=/home/lbakken/log/xstart.log
mkdir -p $logdir

xkbcomp_bin=/usr/bin/xkbcomp
xkbcomp_cfg=/home/lbakken/.xkb
[ -x $xkbcomp_bin ] && [ -f $xkbcomp_cfg ] && $xkbcomp_bin $xkbcomp_cfg :0 >> $logfile 2>&1

alsactl_bin=/usr/bin/alsactl
alsactl_cfg=/home/lbakken/.config/asound.state
[ -x $alsactl_bin ] && [ -f $alsactl_cfg ] && $alsactl_bin --file $alsactl_cfg restore >> $logfile 2>&1

syndaemon_bin=/usr/bin/syndaemon
[ -x $syndaemon_bin ] && $syndaemon_bin -t -k -i 2 >> $logfile 2>&1 &

xrandr_bin=/usr/bin/xrandr
[ -x $xrandr_bin ] && $xrandr_bin --dpi 96 >> $logfile 2>&1 &

xscreensaver_bin=/usr/bin/xscreensaver
[ -x $xscreensaver_bin ] && $xscreensaver_bin -nosplash >> $logfile 2>&1 &

xset_bin=/usr/bin/xset
[ -x $xset_bin ] && [ -f $xset_cfg ] && $xset_bin m 5 2 >> $logfile 2>&1

