#!/bin/sh

# /usr/bin/xset m 5 2
# /usr/bin/xinput set-prop 11 277 -111 -111
# /usr/bin/xkbcomp /home/lbakken/.xkb :0

logdir=/home/lbakken/log
logfile=/home/lbakken/log/xstart.log
mkdir -p $logdir

xkbcomp_bin=/usr/bin/xkbcomp
xkbcomp_cfg=/home/lbakken/.xkb
[ -x $xkbcomp_bin ] && [ -f $xkbcomp_cfg ] && $xkbcomp_bin $xkbcomp_cfg :0 >> $logfile 2>&1

alsactl_bin=/usr/bin/alsactl
alsactl_cfg=/home/lbakken/.config/asound.state
[ -x $alsactl_bin ] && [ -f $alsactl_cfg ] && $alsactl_bin --file $alsactl_cfg restore >> $logfile 2>&1

