if has('win32') || has('win64')
    set guifont=Source_Code_Pro:h10:cANSI
    au GUIEnter * simalt ~x
else
    set guifont=Source\ Code\ Pro\ 10
endif
set guioptions=ar
set guiheadroom=0

set background=dark
colorscheme solarized
