if has('win32') || has('win64')
    let g:ruby_path = 'C:\Rubies\Ruby193\bin'
    set runtimepath=$VIMRUNTIME,$USERPROFILE\\.vim
endif

execute pathogen#infect()

set nocompatible
syntax on

filetype on
filetype indent on
filetype plugin on

if has('win32') || has('win64')
    " NO-OP
elseif has('win32unix')
    set background=dark
    colorscheme solarized
else
    set background=dark
    colorscheme solarized
    set clipboard=unnamedplus
endif

set nu
set ruler
hi LineNr term=NONE

set autoindent
set autowrite
set backup
set backupcopy=yes
set backupdir=$HOME/tmp//,$TEMP//,/tmp//,.//
set dir=$HOME/tmp//,$TEMP//,/tmp//,.//
set expandtab
set formatoptions=cqro
set history=256
set laststatus=2
set nocindent
set nohls
set noincsearch
set shiftround
set shiftwidth=4
set showcmd
set tabstop=4
set viminfo='1024,f1,<500,s256,:1024,rA:,rB:,rD:,h
set wildmenu

" dvorak
map l s
map s l
map n k
map k n
map t j
map j t
map <C-W>j <C-W>t
map <C-W>t <C-W>j
map <C-W>k <C-W>n
map <C-W>n <C-W>k
map gj gt
map gt gj
map gk gn
map gn gk
set noremap
set diffopt=filler,vertical

runtime set_utf8.vim

autocmd FileType dosbatch set encoding=latin1
autocmd FileType dosbatch set fileencoding=latin1

autocmd FileType conf set tabstop=8
autocmd FileType conf set shiftwidth=8
autocmd FileType conf set noexpandtab

autocmd FileType ruby set expandtab
autocmd FileType ruby set shiftwidth=4
autocmd FileType ruby set tabstop=4

autocmd FileType sh set expandtab
autocmd FileType sh set shiftwidth=4
autocmd FileType sh set tabstop=4
autocmd FileType sh set encoding=latin1
autocmd FileType sh set fileencoding=latin1
autocmd FileType sh set fileformat=unix

autocmd FileType perl set expandtab
autocmd FileType perl set shiftwidth=4
autocmd FileType perl set tabstop=4

autocmd FileType coffee set expandtab
autocmd FileType coffee set shiftwidth=2
autocmd FileType coffee set tabstop=2

autocmd FileType python set expandtab
autocmd FileType python set shiftwidth=4
autocmd FileType python set tabstop=4

autocmd FileType html set expandtab
autocmd FileType html set shiftwidth=2
autocmd FileType html set tabstop=2

autocmd FileType yaml set expandtab
autocmd FileType yaml set shiftwidth=2
autocmd FileType yaml set tabstop=2

autocmd FileType json set expandtab
autocmd FileType json set shiftwidth=2
autocmd FileType json set tabstop=2

autocmd FileType xml set expandtab
autocmd FileType xml set shiftwidth=2
autocmd FileType xml set tabstop=2
autocmd FileType html set expandtab
autocmd FileType html set expandtab
autocmd FileType html set shiftwidth=2
autocmd FileType xhtml set tabstop=2
autocmd FileType xhtml set shiftwidth=2
autocmd FileType xhtml set tabstop=2

autocmd FileType markdown set syntax=off
autocmd FileType markdown set expandtab
autocmd FileType markdown set shiftwidth=4
autocmd FileType markdown set tabstop=4
autocmd FileType markdown set textwidth=80
autocmd FileType markdown set formatoptions=t

autocmd FileType sql set expandtab
autocmd FileType sql set shiftwidth=2
autocmd FileType sql set tabstop=2

autocmd FileType go set noexpandtab
autocmd FileType go set shiftwidth=4
autocmd FileType go set tabstop=4
