execute pathogen#infect()

set nocompatible
syntax on

colorscheme solarized
set background=dark

filetype on
filetype indent on
filetype plugin on

set clipboard=unnamedplus

set nu
set ruler
hi LineNr term=NONE
set autoindent
set autowrite
set tabstop=4
set shiftwidth=4
set shiftround
set expandtab
set backup
set backupcopy=yes
set nohls
set noincsearch
set nocindent
set backupdir=$HOME/tmp//,$TEMP//,/tmp//,.//
set dir=$HOME/tmp//,$TEMP//,/tmp//,.//
set viminfo='1000,f1,\"500,:1000,rA:,rB:,rD:,h
set wildmenu
set laststatus=2
set showcmd
set formatoptions=cqro

" dvorak
map l s
map s l
map n k
map k n
map t j
map j t
map <C-W>j <C-W>t
map <C-W>t <C-W>j
map <C-W>k <C-W>n
map <C-W>n <C-W>k
map gj gt
map gt gj
map gk gn
map gn gk
set noremap
set diffopt=filler,vertical

runtime set_utf8.vim

autocmd FileType conf set tabstop=8
autocmd FileType conf set shiftwidth=8
autocmd FileType conf set noexpandtab

autocmd FileType ruby set expandtab
autocmd FileType ruby set shiftwidth=4
autocmd FileType ruby set tabstop=4

autocmd FileType sh set expandtab
autocmd FileType sh set shiftwidth=4
autocmd FileType sh set tabstop=4
autocmd FileType bash set expandtab
autocmd FileType bash set shiftwidth=4
autocmd FileType bash set tabstop=4
autocmd FileType ksh set expandtab
autocmd FileType ksh set shiftwidth=4
autocmd FileType ksh set tabstop=4

autocmd FileType perl set expandtab
autocmd FileType perl set shiftwidth=4
autocmd FileType perl set tabstop=4

autocmd FileType coffee set expandtab
autocmd FileType coffee set shiftwidth=2
autocmd FileType coffee set tabstop=2

autocmd FileType python set expandtab
autocmd FileType python set shiftwidth=4
autocmd FileType python set tabstop=4

autocmd FileType html set expandtab
autocmd FileType html set shiftwidth=2
autocmd FileType html set tabstop=2

autocmd FileType xml set expandtab
autocmd FileType xml set shiftwidth=2
autocmd FileType xml set tabstop=2

autocmd FileType markdown set expandtab
autocmd FileType markdown set shiftwidth=4
autocmd FileType markdown set tabstop=4
autocmd FileType markdown set textwidth=72
autocmd FileType markdown set formatoptions=t
